
import re

# Dictionnaire avec les médias et leurs variations (avec des apostrophes échappées)
media_dict = {
    'Nord Littoral': ['Nord Littoral', 'Nord Littoral ', "NORDLITTORAL"],
    'La Voix du Nord': ['La Voix du Nord', 'La voix du nord', 'La Voix du nord', 'La voix du Nord ', 'LAVOIXDUNORD'],
    'BFM': ['BFM', 'BFM Grand Lille', 'BFM BUSINESS', 'BFMTV Grand Lille', 'BFM LITTORAL '],
    'France Bleu': ['France Bleu', 'France Bleu Nord', 'France bleu', 'France bleu Nord'],
    'France 3': ['France 3', 'France 3 NPDC', 'France 3 Nord pas de calais', 'France 3 npdc'],
    'La Gazette': ['La Gazette', 'La Gazette NPDC', 'La Gazette Nord Pas de Calais', 'La Gazette Nord pas de calais'],
    'La Semaine dans le Boulonnais': ['La Semaine dans le Boulonnais'],
    'France Infos': ['France INFOS', 'France Info', 'France info'],
    'L\'Avenir de l\'Artois': ["L'Avenir de l'Artois", "L'Avenir de l'Artois "],
    'L\'Écho de la Lys': ["L'Echo de la Lys", "L'écho de la lys"],
    'L\'Observateur': ["L'Observateur", "L'Observateur de l'Arrageois", "L'Observateur du Cambrésis", "L'observateur de l'Arrageois", "L'observateur du Cambrésis", "L'observateur du Douaisis", "L'observateur de Douaisis"],
    'Le Courrier de Fourmies': ['Le Courrier de Fourmies', 'Le courrier de Fourmies', 'Le courrier de fourmis', 'Le Courrier de fourmies'],
    'Le Phare Dunkerquois': ['Le Phare Dunkerquois', 'Le phare Dunkerquois', 'le Phare Dunkerquois'],
    'Le Journal des Flandres': ['Le Journal des Flandres', 'Le journal des Flandres'],
    'Delta FM': ['Delta FM', 'delta fm'],
    'Radio 6': ['Radio 6'],
    'RCF': ['RCF radio'],
    'MONAFM': ['MONAFM', 'mona fm'],
    'Nord Éclair': ['Nord Éclair', 'Nord éclair',f'Nord Eclair 2024'],
    'L\'Indépendant': ['L\’independant', 'L\’indépendant', 'L\'independant'],
    'Chérie FM': ['Chéri Fm'],
    'Canal FM': ['Canal FM'],
    'Croix du Nord': ['Croix du Nord', 'Croix du nord hebdomadaire chrétien régional'],
    '20 Minutes': ['20 minutes'],
    'Immodurable': ['Immodurable'],
    'Les Echos du Touquet': ['Les echos du tourquet', 'Les Echos du T ouquet', 'Les echos du tourquet'],
    'Skyrock': ['skyrock'],
    'Horizon': ['horizon'],
    'Site ENLIT': ['Site ENLIT'],
    'Chantiersdefrance.fr': ['Chantiersdefrance.fr'],
    'L\'Abeille de la Ternoise': ["L'Abeille de la Ternoise", "l'abeille de la Ternoise", "l'abeille de la ternoise", 'L\'Abeille De La T ernoise'],
    'La Sambre La Frontière': ['La Sambre La Frontière'],
    'Le Brief Journal des Entreprises': ['Le brief journal des entreprises'],
    'Le Journal des Entreprises': ['Le Journal des Entreprises ', 'Le journal des entreprises'],
    'L\'Indicateur des Flandres': ["L\'Indicateur des Flandres"],
}